spring.datasource.url=jdbc:postgresql://localhost:5433/claimflow
spring.datasource.username=claimflow
spring.datasource.password=claimflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true